{{- if .Values.serviceAccount.create -}}
##################################################################################################
# Associate to Service Mesh
##################################################################################################
apiVersion: maistra.io/v1
kind: ServiceMeshMember
metadata:
  name: default
spec:
  controlPlaneRef:
    name: {{ .Values.smm.controlPlaneRef.name }}
    namespace: {{ .Values.smm.controlPlaneRef.namespace }}
{{- end }}